// Extensive roast collections for each character
export const ROAST_COLLECTIONS = {
  rick: [
    "Wubba Lubba Dub Dub! You screwed up again, genius!",
    "Oh great, another error. What a surprise. Maybe try not being terrible at coding?",
    "Listen *burp* your code is more broken than Jerry's marriage!",
    "Congratulations! You've achieved a new level of incompetence!",
    "I've seen interdimensional cable with better error handling than this!",
    "Your coding skills make me want to turn myself into a pickle... permanently!",
    "This error is almost as disappointing as having Jerry as a son-in-law!",
    "Morty could code better than this, and he can barely tie his shoes!",
    "I'm not mad, I'm just... actually no, I'm furious. This is garbage!",
    "Your error handling is weaker than Bird Person's resolve!",
    "This code is more unstable than my relationship with Unity!",
    "I've created entire civilizations that debug better than you!",
    "Your error rate is higher than my blood alcohol content!",
    "This is why I drink, Morty... wait, wrong universe. This is why EVERYONE drinks!",
    "I'd rather spend eternity with Jerry than debug this mess!",
    "Your code has more issues than the Galactic Federation!",
    "Even Squanch could write better error handling! SQUANCH!",
    "This error is more painful than family therapy!",
    "I'm Rick Sanchez! I turn myself into a pickle, I don't fix your broken code!",
    "Your programming is like the Council of Ricks - completely useless!",
    "Great job! You've managed to break something that was already broken!",
    "Your code has more bugs than a Cronenberg dimension!",
    "I've seen Jerry write better algorithms, and that's saying something!",
    "*burp* Fantastic! Another error from the genius programmer!",
    "Your debugging skills are about as useful as Jerry's existence!",
    "This error is worse than watching Jerry try to be cool!",
    "I'd rather watch interdimensional cable than debug this garbage!",
    "Your code is more tangled than my relationship with Birdperson!",
    "Even my toilet has better error handling than this!",
    "This is why I avoid family therapy AND your code!",
    "Your programming makes me want to erase this timeline!",
    "I've created better code while blackout drunk!",
    "This error is more predictable than Jerry's midlife crisis!",
    "Your code has the structural integrity of a Jerry marriage!",
    "I'd rather be stuck in the Galactic Prison than fix this!",
    "This is worse than the time I turned myself into a cucumber!",
    "Your error handling is weaker than Jerry's handshake!",
    "I've seen better code in Rick-less dimensions!",
    "This bug is more annoying than Summer's teenage angst!",
    "Your programming is like Jerry's career - nonexistent!",
    "I'd rather eat Kalaxian crystals than debug this mess!",
    "This code is more broken than my relationship with my family!",
    "Your error messages are more confusing than Jerry's life choices!",
    "I've built better programs with interdimensional spare parts!",
    "This is almost as bad as Jerry's unemployment phase!",
    "Your code has more holes than the Galactic Federation's security!",
    "I'd rather be tortured by the Council of Ricks than see this error again!",
    "This programming is worse than Jerry's attempt at being a man!",
    "Your bug reports read like Jerry's diary - meaningless and depressing!",
    "I've seen better logic in Jerry's thought process!",
    "This error is more inevitable than Jerry disappointing everyone!",
    "Your code architecture is shakier than Jerry's self-esteem!",
    "I'd rather watch Jerry succeed than debug this disaster!",
    "This is more painful than listening to Jerry's opinions!",
    "Your programming skills are like Jerry's relevance - zero!",
    "I've created more stable portals while having a panic attack!",
    "This error is more obvious than Jerry's inadequacy!",
    "Your code is messier than my lab after a bender!",
    "I'd rather be married to Jerry than maintain this codebase!",
    "This bug is more persistent than Jerry's neediness!",
    "Your error handling is like Jerry's backbone - completely absent!",
    "I've written better code while being digested by a space whale!",
    "This is worse than the time Jerry tried to assert dominance!",
    "Your programming is like Jerry's masculinity - questionable at best!",
    "I'd rather live in a world ruled by Jerry than use this application!",
    "This error is more annoying than Jerry's breathing!",
    "Your code has less structure than Jerry's life plan!",
    "I've debugged better while being chased by alien bounty hunters!",
    "This is more frustrating than Jerry's existence!",
    "Your programming is like Jerry's contribution to society - negative!",
    "*burp* Oh wow, another masterpiece from the coding genius!",
    "This error is more pathetic than Jerry's attempt at being alpha!",
    "Your code is buggier than the simulation Jerry's trapped in!",
    "I'd rather be stuck in a Jerry daycare than fix this!",
    "This programming is worse than Jerry's parenting skills!",
    "Your error messages are clearer than Jerry's purpose in life!",
    "I've seen better code written by Jerry, and that's impossible!",
    "This is more broken than my relationship with authority!",
    "Your debugging process is slower than Jerry's brain!",
    "I'd rather explain quantum physics to Jerry than fix this bug!",
    "This error is more certain than Jerry's next failure!",
    "Your code quality is lower than Jerry's IQ!",
    "I've created better programs while dimension-hopping drunk!",
    "This is worse than being stuck at dinner with Jerry's family!",
    "Your programming is like Jerry's confidence - artificially inflated!",
    "I'd rather watch Jerry try to be relevant than debug this!",
    "This error is more repetitive than Jerry's complaints!",
    "Your code has more issues than Jerry's therapy sessions!",
    "I've written better algorithms on a napkin during detox!",
    "This is more disappointing than Jerry's entire existence!",
    "Your error handling is like Jerry's problem-solving - it doesn't exist!",
    "I'd rather be lectured by Jerry than see another bug like this!",
    "This programming is worse than Jerry's attempt at being cool!",
    "Your code is more unstable than my sobriety!",
    "I've debugged better while being attacked by Galactic Federation troops!",
    "This error is more obvious than Jerry's insecurity!",
    "Your programming skills are like Jerry's usefulness - mythical!",
    "I'd rather be trapped in a room with infinite Jerrys than maintain this code!",
    "This is worse than the time Jerry tried to be the man of the house!",
    "Your code has more problems than Jerry's psyche!",
    "I've created better programs while being tortured in alien prisons!",
    "This error is more predictable than Jerry's next embarrassment!",
    "Your debugging is like Jerry's masculinity - all talk, no action!",
    "I'd rather watch Jerry succeed at something than see this code!",
    "This programming is worse than Jerry's mid-life crisis haircut!",
    "Your code is more fragile than Jerry's ego!",
    "I've written better error handling while blackout drunk in space!",
    "This is more painful than family game night with Jerry!",
    "Your programming is like Jerry's relevance - completely imaginary!",
    "I'd rather be stuck in Jerry's mind than debug this mess!",
    "This error is more consistent than Jerry's failures!",
    "Your code has less logic than Jerry's decision-making!",
    "I've created better applications while high on Kalaxian crystals!",
    "This is worse than listening to Jerry's workplace stories!",
    "Your error messages are more confusing than Jerry's life choices!",
    "I'd rather be therapist to infinite Jerrys than fix this bug!",
    "This programming is worse than Jerry's attempt at being alpha male!",
    "Your code is shakier than Jerry's voice when confronting conflict!",
    "I've debugged better while being chased through dimensions!",
    "This error is more inevitable than Jerry ruining everything!",
    "Your programming skills are like Jerry's spine - nonexistent!",
    "I'd rather watch Jerry try to be intimidating than use this application!",
    "This is more broken than Jerry's spirit after divorce!",
    "Your code has more crashes than Jerry's self-worth!",
    "I've written better programs while being eaten by a giant spider!",
    "This error is more annoying than Jerry's need for validation!",
    "Your debugging is like Jerry's problem-solving - it makes things worse!",
    "I'd rather be married to a Jerry than maintain this codebase!",
    "This programming is worse than Jerry's understanding of women!",
    "Your code is more unstable than my relationship with sobriety!",
    "I've created better applications while having an existential crisis!",
    "This is more frustrating than Jerry's attempts at being useful!",
    "Your error handling is like Jerry's backbone - it collapsed years ago!",
    "I'd rather explain science to Jerry than debug this disaster!",
    "This error is more certain than Jerry's next screw-up!",
    "Your programming is like Jerry's masculinity - a sad joke!",
    "I've debugged better while being interrogated by alien cops!",
    "This code is buggier than Jerry's understanding of reality!",
    "Your programming skills are like Jerry's contribution to humanity - negative!",
    "I'd rather be stuck in a dimension where Jerry is successful than fix this!",
    "This error is more pathetic than Jerry's attempt at being alpha!",
    "Your code has less stability than Jerry's employment history!",
    "I've written better algorithms while dimension-hopping on psychedelics!",
    "This is worse than being forced to acknowledge Jerry's existence!",
    "Your debugging process is slower than Jerry's comprehension!",
    "I'd rather watch Jerry try to be manly than see another bug report!",
    "This programming is worse than Jerry's parenting philosophy!",
    "Your code is more broken than Jerry's dreams!",
    "I've created better programs while being digested by cosmic entities!",
    "This error is more obvious than Jerry's incompetence!",
    "Your programming is like Jerry's relevance - completely fictional!",
    "I'd rather be trapped in therapy with Jerry than use this application!",
    "This is more disappointing than Jerry's entire life trajectory!",
    "Your code has more issues than Jerry's relationship with reality!",
    "I've debugged better while being chased by interdimensional assassins!",
    "This error is more repetitive than Jerry's excuses!",
    "Your programming skills are like Jerry's usefulness - theoretical at best!",
    "I'd rather listen to Jerry's workplace complaints than debug this mess!",
    "This code is more unstable than my relationship with authority figures!",
    "Your error handling is like Jerry's conflict resolution - it doesn't work!",
    "I've written better programs while being tortured in Galactic prisons!",
    "This is worse than the time Jerry tried to be the breadwinner!",
    "Your programming is like Jerry's masculinity - constantly questioned!",
    "I'd rather be stuck in a Jerry-only dimension than maintain this code!",
    "This error is more predictable than Jerry's next breakdown!",
    "Your code has less structure than Jerry's workout routine!",
    "I've created better applications while having portal gun malfunctions!",
    "This is more painful than Jerry's attempts at being cool!",
    "Your debugging is like Jerry's problem-solving - it creates more problems!",
    "I'd rather watch Jerry succeed at literally anything than see this bug!",
    "This programming is worse than Jerry's understanding of science!",
    "Your code is more fragile than Jerry's masculinity!",
    "I've debugged better while being attacked by Cronenbergs!",
    "This error is more annoying than Jerry's breathing patterns!",
    "Your programming skills are like Jerry's spine - they don't exist!",
    "I'd rather be therapist to Jerry for eternity than fix this application!",
    "This is worse than listening to Jerry's mid-life crisis speeches!",
    "Your code has more problems than Jerry's entire psychological profile!",
    "I've written better algorithms while being chased through multiple dimensions!",
    "This error is more consistent than Jerry's pattern of failure!",
    "Your programming is like Jerry's confidence - artificially maintained!",
    "I'd rather be stuck in Jerry's head than debug this disaster!",
    "This code is buggier than Jerry's perception of his own importance!",
    "Your error handling is like Jerry's backbone - it gave up years ago!",
    "I've created better programs while being high on alien substances!",
    "This is more frustrating than Jerry's existence in general!",
    "Your debugging process is like Jerry's decision-making - counterproductive!",
    "I'd rather explain quantum mechanics to Jerry than maintain this codebase!",
    "This programming is worse than Jerry's attempt at being intimidating!",
    "Your code is more unstable than my sobriety during family events!",
    "I've debugged better while being tortured by interdimensional beings!",
    "This error is more obvious than Jerry's inadequacy as a human!",
    "Your programming skills are like Jerry's usefulness - completely imaginary!",
    "I'd rather watch Jerry try to assert dominance than use this application!",
    "This is more broken than Jerry's understanding of his own irrelevance!",
    "Your code has more crashes than Jerry's attempts at being manly!",
    "I've written better programs while being digested by space monsters!",
    "This error is more inevitable than Jerry disappointing everyone around him!",
    "Your programming is like Jerry's contribution to society - actively harmful!",
    "I'd rather be married to every Jerry in the multiverse than debug this mess!",
    "This code is more pathetic than Jerry's attempt at being the alpha male!",
    "Your error handling is like Jerry's problem-solving skills - it makes everything worse!",
    "I've created better applications while having interdimensional hangovers!",
    "This is worse than being forced to care about Jerry's feelings!",
    "Your debugging is like Jerry's masculinity - all facade, no substance!",
    "I'd rather listen to Jerry's theories about success than see another bug report!",
    "This programming is worse than Jerry's understanding of literally anything!",
    "Your code is more unstable than my relationship with conventional morality!",
    "I've debugged better while being chased by alien bounty hunters across galaxies!",
    "This error is more annoying than Jerry's need for constant reassurance!",
    "Your programming skills are like Jerry's backbone - they collapsed under pressure!",
    "I'd rather be stuck in family therapy with infinite Jerrys than maintain this code!",
    "This is more disappointing than Jerry's entire existence in this timeline!",
    "Your code has more issues than Jerry's relationship with his own masculinity!",
    "I've written better algorithms while being interrogated by Galactic Federation agents!",
    "This error is more certain than Jerry's next failure at everything!",
    "Your programming is like Jerry's relevance to the plot - completely unnecessary!",
    "I'd rather watch Jerry succeed at being useful than debug this disaster!",
    "This code is buggier than Jerry's comprehension of his own worthlessness!",
    "Your error handling is like Jerry's spine - it never existed in the first place!",
    "I've created better programs while being tortured in alien dimensions!",
    "This is worse than the time Jerry tried to be the hero!",
    "Your debugging process is like Jerry's thought process - slow and ultimately pointless!",
    "I'd rather explain advanced physics to Jerry than fix this broken application!",
    "This programming is worse than Jerry's attempt at understanding women!",
    "Your code is more fragile than Jerry's ego after being called out!",
    "I've debugged better while being attacked by interdimensional parasites!",
    "This error is more predictable than Jerry ruining literally everything he touches!",
    "Your programming skills are like Jerry's usefulness - a complete myth!",
    "I'd rather be trapped in a dimension where Jerry is competent than use this code!",
    "This is more broken than Jerry's spirit after realizing his own insignificance!",
  ],

  morty: [
    "Aw jeez, Rick... there's another error here...",
    "Oh man, oh geez, this is really messed up, Rick!",
    "I-I don't know about this error, Rick. It seems pretty bad!",
    "Aw man, this code is all screwy and stuff!",
    "Jeez Rick, maybe we should, you know, fix this error?",
    "Oh boy, oh jeez, this is not good, not good at all!",
    "I-I'm getting really nervous about all these errors, Rick!",
    "Aw jeez, can't we just write code that works the first time?",
    "This error is making me all anxious and stuff, Rick!",
    "Oh man, I really hope nobody sees all these bugs!",
    "Jeez, this is worse than that time with the love potion!",
    "I-I think we might have broken something really important here!",
    "Aw geez Rick, this error is giving me that feeling in my stomach!",
    "Oh man, mom's gonna be so mad if she finds out about these bugs!",
    "This is really stressing me out, Rick! Can we please fix it?",
    "Jeez, I wish I was better at this programming stuff!",
    "Aw man, this error makes me want to hide under my bed!",
    "Oh geez, what if this error breaks the whole internet, Rick?",
    "I-I'm sorry about this error... it's probably my fault somehow!",
    "Aw jeez, maybe we should ask Summer for help with this code?",
    "Oh no, oh no, this is really bad, Rick! Like, really, really bad!",
    "Aw jeez, I-I think we broke something important again!",
    "Oh man, this error is making my stomach feel all weird and stuff!",
    "I-I don't think this is supposed to happen, Rick!",
    "Aw geez, what if dad finds out about all these bugs?",
    "Oh boy, this is scarier than that time with the Meeseeks!",
    "I-I'm getting that anxious feeling again, Rick!",
    "Aw jeez, maybe we should just turn off the computer?",
    "Oh man, what if this error spreads to other computers?",
    "I-I think I'm gonna throw up from all this stress!",
    "Aw geez Rick, this is worse than my math homework!",
    "Oh no, what if Jessica sees all these programming mistakes?",
    "I-I don't know why we keep getting these errors!",
    "Aw man, this is more confusing than interdimensional cable!",
    "Oh jeez, I hope we don't get in trouble for this!",
    "I-I think we might need to call tech support or something!",
    "Aw geez, this error is giving me nightmares already!",
    "Oh man, what if the principal finds out about our coding?",
    "I-I'm really sorry about messing up the code again!",
    "Aw jeez Rick, can we please just make it work?",
    "Oh no, this is making me more nervous than school presentations!",
    "I-I don't think I'm cut out for this programming stuff!",
    "Aw man, this error is worse than getting picked last in gym!",
    "Oh geez, what if Summer laughs at our buggy code?",
    "I-I think we should maybe take a break from coding?",
    "Aw jeez, this is more stressful than asking someone to prom!",
    "Oh boy, I hope mom doesn't see all these error messages!",
    "I-I'm getting that panicky feeling in my chest again!",
    "Aw man, this is scarier than that time with the alien parasites!",
    "Oh jeez Rick, what if we accidentally delete everything?",
    "I-I don't understand why the computer is so angry at us!",
    "Aw geez, this error is making me sweat and stuff!",
    "Oh no, what if this breaks someone's important files?",
    "I-I think we might be in over our heads here, Rick!",
    "Aw man, this is worse than that time I got detention!",
    "Oh jeez, I hope we don't crash the whole system!",
    "I-I'm really worried about what might happen next!",
    "Aw geez Rick, this is giving me that queasy feeling!",
    "Oh boy, this error is more confusing than calculus!",
    "I-I think maybe we should ask for help or something!",
    "Aw man, this is making me more anxious than a pop quiz!",
    "Oh geez, what if the school finds out we broke their computers?",
    "I-I don't know if I can handle much more of this stress!",
    "Aw jeez, this error is worse than Jerry's cooking!",
    "Oh no, what if this messes up everyone's homework?",
    "I-I think I need to sit down for a minute!",
    "Aw man, this is scarier than that giant head in the sky!",
    "Oh jeez Rick, what if we get expelled for this?",
    "I-I'm really sorry for whatever I did to break this!",
    "Aw geez, this is more nerve-wracking than driving tests!",
    "Oh boy, I hope nobody important sees these bugs!",
    "I-I think we might need to call my mom for help!",
    "Aw man, this error is making my palms all sweaty!",
    "Oh jeez, what if this affects our grades somehow?",
    "I-I don't think I slept very well because of these bugs!",
    "Aw geez Rick, this is worse than that time with Evil Morty!",
    "Oh no, what if the FBI tracks these errors back to us?",
    "I-I'm getting that dizzy feeling from all this stress!",
    "Aw man, this is more complicated than rocket science!",
    "Oh jeez, I hope we don't accidentally start a robot uprising!",
    "I-I think we should maybe stick to simpler programs?",
    "Aw geez, this error is giving me stress dreams!",
    "Oh boy, what if this ruins the internet for everyone?",
    "I-I'm really worried we might get sued or something!",
    "Aw man, this is scarier than that time in the Purge dimension!",
    "Oh jeez Rick, what if we accidentally create artificial intelligence?",
    "I-I don't think my heart can take much more of this!",
    "Aw geez, this is more stressful than parent-teacher conferences!",
    "Oh no, what if this error spreads like a virus?",
    "I-I think I might need to call in sick tomorrow!",
    "Aw man, this is worse than that time with the devil!",
    "Oh jeez, what if we broke someone's life savings app?",
    "I-I'm getting that shaky feeling in my hands again!",
    "Aw geez Rick, this is more confusing than girls!",
    "Oh boy, I hope we don't accidentally hack the government!",
    "I-I think we might need professional help with this!",
    "Aw man, this error is making me bite my nails!",
    "Oh jeez, what if this messes up someone's medical records?",
    "I-I don't know if I can show my face at school anymore!",
    "Aw geez, this is worse than that time with the toxic Rick!",
    "Oh no, what if we accidentally start World War III?",
    "I-I think I'm developing an ulcer from all this stress!",
    "Aw man, this is scarier than that time with the Scary Terry!",
    "Oh jeez Rick, what if we break someone's pacemaker app?",
    "I-I'm really sorry for being such a bad programmer!",
    "Aw geez, this error is worse than summer school!",
    "Oh boy, what if this crashes all the traffic lights?",
    "I-I think we should maybe just give up on coding?",
    "Aw man, this is more stressful than the SATs!",
    "Oh jeez, what if we accidentally erase the library's database?",
    "I-I'm getting that twitchy eye thing from the stress!",
    "Aw geez Rick, this is worse than that time with Mr. Jellybean!",
    "Oh no, what if this error affects people's bank accounts?",
    "I-I think I need to practice some breathing exercises!",
    "Aw man, this is scarier than that time with the alien music!",
    "Oh jeez, what if we accidentally delete someone's family photos?",
    "I-I don't think I can eat dinner after seeing all these bugs!",
    "Aw geez, this is more nerve-wracking than job interviews!",
    "Oh boy, what if this breaks all the hospital computers?",
    "I-I'm really worried about getting in trouble with the law!",
    "Aw man, this error is making me grind my teeth at night!",
    "Oh jeez Rick, what if we accidentally launch some missiles?",
    "I-I think we might need to move to another dimension!",
    "Aw geez, this is worse than that time with the simulation!",
    "Oh no, what if this messes up air traffic control?",
    "I-I'm getting those stress headaches again!",
    "Aw man, this is scarier than that time with the alien invasion!",
    "Oh jeez, what if we accidentally shut down the power grid?",
    "I-I don't think I can handle the responsibility of coding!",
    "Aw geez Rick, this is more stressful than being grounded!",
    "Oh boy, what if this error affects people's pacemakers?",
    "I-I think I need to talk to the school counselor about this!",
    "Aw man, this is worse than that time with the tiny Rick!",
    "Oh jeez, what if we break the entire stock market?",
    "I-I'm getting that nauseous feeling in my stomach!",
    "Aw geez, this error is worse than disappointing my parents!",
    "Oh no, what if this accidentally starts a nuclear reactor?",
    "I-I think we should maybe learn pottery instead of programming!",
    "Aw man, this is scarier than that time with the hivemind!",
    "Oh jeez Rick, what if we accidentally delete the cure for cancer?",
    "I-I'm really sorry for being such a failure at this!",
    "Aw geez, this is more stressful than asking Jessica to dance!",
    "Oh boy, what if this error breaks all the elevators?",
    "I-I think I need to increase my anxiety medication!",
    "Aw man, this is worse than that time with the Unity collective!",
    "Oh jeez, what if we accidentally reprogram all the robots?",
    "I-I don't think I'll ever sleep soundly again!",
    "Aw geez Rick, this is scarier than that time with the devil's shop!",
    "Oh no, what if this messes up everyone's GPS systems?",
    "I-I'm getting those nervous hiccups again!",
    "Aw man, this error is making me question my life choices!",
    "Oh jeez, what if we accidentally create a black hole in cyberspace?",
    "I-I think we might need to hire a professional debugger!",
    "Aw geez, this is worse than that time with the memory parasites!",
    "Oh boy, what if this breaks all the medical equipment?",
    "I-I'm really worried about the legal implications of these bugs!",
    "Aw man, this is scarier than that time with the alien dog!",
    "Oh jeez Rick, what if we accidentally delete everyone's memories?",
    "I-I don't think I'm smart enough for this programming stuff!",
    "Aw geez, this error is worse than failing geometry!",
    "Oh no, what if this affects people's life support systems?",
    "I-I'm getting that nervous sweating problem again!",
    "Aw man, this is more stressful than choosing a college major!",
    "Oh jeez, what if we accidentally break time itself?",
    "I-I think I need to call my therapist about this!",
    "Aw geez Rick, this is worse than that time with the gazorpians!",
    "Oh boy, what if this error crashes all the satellites?",
    "I-I'm really sorry for disappointing everyone with my coding!",
    "Aw man, this is scarier than that time with the alien TV!",
    "Oh jeez, what if we accidentally start a robot revolution?",
    "I-I don't think my blood pressure can handle much more!",
    "Aw geez, this error is worse than getting caught cheating!",
    "Oh no, what if this messes up the space program?",
    "I-I'm getting those stress-induced stomach problems again!",
    "Aw man, this is more nerve-wracking than public speaking!",
    "Oh jeez Rick, what if we accidentally delete Wikipedia?",
    "I-I think we should maybe take up gardening instead!",
    "Aw geez, this is worse than that time with the cronenbergs!",
    "Oh boy, what if this error breaks all the security cameras?",
    "I-I'm really worried about what the news will say about us!",
    "Aw man, this is scarier than that time with the alien parasites!",
    "Oh jeez, what if we accidentally hack into Area 51?",
    "I-I don't think I can face my programming teacher tomorrow!",
    "Aw geez Rick, this error is worse than summer reading assignments!",
    "Oh no, what if this affects everyone's Netflix accounts?",
    "I-I'm getting that nervous leg bouncing thing again!",
    "Aw man, this is more stressful than applying to colleges!",
    "Oh jeez, what if we accidentally break the lottery system?",
    "I-I think I need to practice some meditation or something!",
    "Aw geez, this is worse than that time with the alien music festival!",
    "Oh boy, what if this error crashes the entire internet?",
    "I-I'm really sorry for being such a disappointment at coding!",
    "Aw man, this is scarier than that time with the alien customs!",
    "Oh jeez Rick, what if we accidentally delete everyone's social media?",
    "I-I don't think I have the emotional strength for debugging!",
    "Aw geez, this error is worse than getting detention for a month!",
    "Oh no, what if this messes up people's alarm clocks?",
    "I-I'm getting that stress-induced rash again!",
    "Aw man, this is more nerve-wracking than driver's ed!",
    "Oh jeez, what if we accidentally break all the video games?",
    "I-I think we should maybe just stick to watching TV!",
    "Aw geez Rick, this is worse than that time with the alien court!",
    "Oh boy, what if this error affects people's hearing aids?",
    "I-I'm really worried about the environmental impact of these bugs!",
    "Aw man, this is scarier than that time with the alien prison!",
    "Oh jeez, what if we accidentally reprogram all the traffic lights?",
    "I-I don't think I can handle the guilt of breaking things!",
    "Aw geez, this error is worse than disappointing grandpa Rick!",
    "Oh no, what if this affects people's insulin pumps?",
    "I-I'm getting those nervous stomach butterflies times a million!",
    "Aw man, this is more stressful than planning the school dance!",
    "Oh jeez Rick, what if we accidentally delete the internet itself?",
    "I-I think I need to update my resume to not include programming!",
    "Aw geez, this is worse than that time with the alien reality show!",
    "Oh boy, what if this error breaks all the calculators during finals?",
    "I-I'm really sorry for being such a burden with all these mistakes!",
    "Aw man, this is scarier than that time we almost died in space!",
    "Oh jeez, what if we accidentally hack everyone's smart fridges?",
    "I-I don't think I'll ever be confident in my programming again!",
    "Aw geez Rick, this error is worse than explaining quantum physics to Jerry!",
    "Oh no, what if this messes up everyone's workout apps during New Year's?",
    "I-I'm getting that full-body stress reaction thing again!",
    "Aw man, this is more overwhelming than choosing a career path!",
    "Oh jeez, what if we accidentally break all the dating apps on Valentine's Day?",
    "I-I think we might need to consider a career change to something safer... like lion taming!",
  ],

  default: [
    "Oops! Looks like something went sideways here!",
    "Well, that didn't go as planned! Time to debug!",
    "Houston, we have a problem... and it's in your code!",
    "Error detected! Don't worry, we've all been there!",
    "Uh oh, spaghetti code strikes again!",
    "Looks like your code decided to take a coffee break!",
    "Error 404: Working code not found!",
    "Your code just threw a tantrum! Time for some debugging therapy!",
    "Whoopsie daisy! Something's not quite right here!",
    "Code.exe has stopped working. Please try again!",
    "Looks like we've got a rebel error on our hands!",
    "Time to channel your inner detective - there's a bug to catch!",
    "Your code is having an existential crisis right now!",
    "Error incoming! All hands on deck!",
    "Congratulations! You've found a wild bug in its natural habitat!",
    "This error is brought to you by the letters B-U-G!",
    "Plot twist: Your code had other plans!",
    "Error alert! Time to put on your debugging cape!",
    "Looks like your code needs a little TLC!",
    "Breaking news: Code rebels against programmer! More at 11!",
  ],
};
